spring.datasource.url=jdbc:mysql://localhost:3306/smart_farmer_app?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=Pawan@99
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.sql.init.continue-on-error=false
spring.jpa.defer-datasource-initialization=true

weather.api.key=277d13ffd5bdf85e14af0cc482067bde
weather.api.lat=26.9124
weather.api.lon=75.7873
weather.api.units=metric
weather.api.timezone=Asia/Kolkata

server.port=8080
